### ISSUE TITLE
panic: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by aiyuzhou** [gwduan/beego-demo#10]
**when I run 'bee run':**
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.0
2018/03/13 18:51:11 INFO     ▶ 0001 Using 'beego-demo' as 'appname'
2018/03/13 18:51:11 INFO     ▶ 0002 Initializing watcher...
2018/03/13 18:51:13 SUCCESS  ▶ 0003 Built Successfully!
2018/03/13 18:51:13 INFO     ▶ 0004 Restarting 'beego-demo'...
2018/03/13 18:51:13 SUCCESS  ▶ 0005 './beego-demo' is running...
panic: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)

goroutine 1 [running]:
panic(0x52b6c0, 0xc420188580)
	/usr/local/go1.7.3/src/runtime/panic.go:500 +0x1a1
beego-demo/models/mymysql.init.1()
	/Users/annie/code/golang/src/beego-demo/models/mymysql/mymysql.go:26 +0x106
beego-demo/models/mymysql.init()
	/Users/annie/code/golang/src/beego-demo/models/mymysql/mymysql.go:31 +0x3d
beego-demo/models.init()
	/Users/annie/code/golang/src/beego-demo/models/users_io.go:38 +0x3d
beego-demo/controllers.init()
	/Users/annie/code/golang/src/beego-demo/controllers/users.go:271 +0x71
main.init()
	/Users/annie/code/golang/src/beego-demo/main.go:46 +0x42

**Then I change the password to my root password and re-run:**

______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.0
2018/03/13 18:52:54 INFO     ▶ 0001 Using 'beego-demo' as 'appname'
2018/03/13 18:52:54 INFO     ▶ 0002 Initializing watcher...
2018/03/13 18:52:55 SUCCESS  ▶ 0003 Built Successfully!
2018/03/13 18:52:55 INFO     ▶ 0004 Restarting 'beego-demo'...
2018/03/13 18:52:55 SUCCESS  ▶ 0005 './beego-demo' is running...
panic: Error 1044: Access denied for user 'root'@'localhost' to database 'beego_demo'

goroutine 1 [running]:
panic(0x52b6c0, 0xc420188580)
	/usr/local/go1.7.3/src/runtime/panic.go:500 +0x1a1
beego-demo/models/mymysql.init.1()
	/Users/annie/code/golang/src/beego-demo/models/mymysql/mymysql.go:26 +0x106
beego-demo/models/mymysql.init()
	/Users/annie/code/golang/src/beego-demo/models/mymysql/mymysql.go:31 +0x3d
beego-demo/models.init()
	/Users/annie/code/golang/src/beego-demo/models/users_io.go:38 +0x3d
beego-demo/controllers.init()
	/Users/annie/code/golang/src/beego-demo/controllers/users.go:271 +0x71
main.init()
	/Users/annie/code/golang/src/beego-demo/main.go:46 +0x42

**Do I need to create database'beego_demo' myself? or it already exised? how can I get access to it?**

**Comment by aiyuzhou** [comment]
Then I tried to run 'CREATE DATABASE IF NOT EXISTS beego_demo;'

mysql> CREATE DATABASE IF NOT EXISTS beego_demo;
ERROR 1044 (42000): Access denied for user 'root'@'localhost' to database 'beego_demo'
mysql>

Any idea?
